### ISSUE TITLE
[Bug] typos and grammar in some of the step markdown files

### ISSUE THREAD

**Issue by mjbear** [skills/introduction-to-codeql#15]
### Summary

Fix a few typos and grammar related items in a few of the step markdown files.

### How to reproduce

[line 27](https://github.com/skills/introduction-to-codeql/blob/main/.github/steps/1-enable-codeql.md?plain=1#L27)
Step 1: Enable CodeQL
Navigate ~~the to~~ [to the] Settings tab at the top of your newly created repository.
^ reorder "the to" to "to the"

[line 83](https://github.com/skills/introduction-to-codeql/blob/main/.github/steps/2-review-and-triage-codeql-alerts.md?plain=1#L83)
Step 2: Review and Triage CodeQL Alerts
Open one of the open alerts that CodeQL [identified] from the scan.

[line 12](https://github.com/skills/introduction-to-codeql/blob/main/.github/steps/4-prevent-vulnerabilities-in-the-pull-request.md?plain=1#L12)
Step 4: Prevent Vulnerabilities in the Pull Request
This is going to be the same issue [we] initially saw.

[line 12](https://github.com/skills/introduction-to-codeql/blob/main/.github/steps/X-finish.md?plain=1#L12)
Finish
CodeQL scanned the code in your repository and notified us of two SQL injection ~~vulenrabilities~~ [vulnerabilities].

### Additional context

Please see the hyperlinks above.

**Comment by nguyenalex836** [comment]
@mjbear Thank you for submitting this issue, and linking your [PR](https://github.com/skills/introduction-to-codeql/pull/16)! We will get the PR you linked triaged for review ✨
